# -*- coding: utf-8 -*-
"""flight_delay_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Gp4ngOyDs-uoJBbMoi7Wkpn2UXamIUr
"""

import os
import joblib
import streamlit as st
import pandas as pd


# Load the model from file
with open("flight_delay_model.pkl", "rb") as f:
    model = joblib.load(f)

# Define the user interface
st.header('Flight Delay Prediction')

# Define the model prediction logic
def predict_delay(year, month, carrier_name, airport_name, late_aircraft_delay,
                  carrier_delay, nas_delay, weather_delay):
    input_df = pd.DataFrame({
        'year': [year],
        'month': [month],
        'carrier_name': [carrier_name],
        'airport_name': [airport_name],
        'late_aircraft_delay': [late_aircraft_delay],
        'carrier_delay': [carrier_delay],
        'nas_delay': [nas_delay],
        'weather_delay': [weather_delay]})
    prediction = model.predict(input_df)
    return prediction[0]

# Define the user interface
def main():
  st.title('Flight Delay Prediction')

  year = st.number_input('Year', min_value=2018, max_value=2022, value=2018)
  month = st.number_input('Month', min_value=1, max_value=12, value=6)
  carrier_name = st.selectbox('Carrier Name', ['SkyWest Airlines Inc.','Delta Air Lines Inc.',       
                                               'Envoy Air','Allegiant Air','American Airlines Inc.',       
                                               'United Air Lines Inc.','Mesa Airlines Inc.','Endeavor Air Inc.',            
                                               'Southwest Airlines Co.','Frontier Airlines Inc.','Republic Airline',             
                                               'PSA Airlines Inc.','Alaska Airlines Inc.','JetBlue Airways',              
                                               'Spirit Air Lines','ExpressJet Airlines Inc.','ExpressJet Airlines LLC',      
                                               'Horizon Air','Hawaiian Airlines Inc.','Virgin America'])
  airport_name = st.selectbox('Airport Name', ['Pittsburgh, PA: Pittsburgh International',                      
                                                'Nashville, TN: Nashville International',                       
                                                'Raleigh/Durham, NC: Raleigh-Durham International',              
                                                'New Orleans, LA: Louis Armstrong New Orleans International',   
                                                'Cleveland, OH: Cleveland-Hopkins International '])
  late_aircraft_delay = st.number_input('Late Aircraft Delay', min_value=0, max_value=10000, value=0)
  carrier_delay = st.number_input('Carrier Delay', min_value=0, max_value=10000, value=0)
  nas_delay = st.number_input('NAS Delay', min_value=0, max_value=10000, value=0)
  weather_delay = st.number_input('Weather Delay', min_value=0, max_value=10000, value=0)

  if st.button('Predict Delay'):   
      prediction = predict_delay(year, month, carrier_name, airport_name, late_aircraft_delay,
                  carrier_delay, nas_delay, weather_delay)
      st.write('The predicted flight delay is:', 'Delayed' if prediction == 1 else 'Not Delayed')

if __name__ == "__main__":
  main()